# Generated by Django 2.2.4 on 2019-08-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='ip_address',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
