# Generated by Django 2.2.4 on 2019-08-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_person_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='fail_login_attempts',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
